<?php
/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

namespace app\assets;

use yii\web\AssetBundle;
use app\common\services\UrlService;

/**
 * Main application asset bundle.
 *
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @since 2.0
 */
class WebAsset extends AssetBundle
{
    public $basePath = '@webroot';
    public $baseUrl = '@web';
    public $css = [
        'css/site.css',
    ];
    public $js = [
    ];
    public function registerAssetFiles($view)
    {
        // 添加版本号
        $release_version = defined("RELEASE_VERSION")?RELEASE_VERSION:time();
        $this->css = [
            UrlService::buildUrl("/bootstrap/css/bootstrap.min.css", ['var'=>$release_version]),
            UrlService::buildUrl("/font-awesome/css/font-awesome.min.css", ['var'=>$release_version]),
            UrlService::buildUrl("/css/www/style.css", ['var'=>$release_version])
        ];

        parent::registerAssetFiles($view); // TODO: Change the autogenerated stub
    }
}
